### PR TITLE
Feat/offline stock

### PR DESCRIPTION
**Pull request by freefony**

### CODE REVIEW

**Comment by jofomah** [comment]
@freefony this is replica of my PR that has been merged in, so i will close it because it does not contain any new feature.

**Comment by freefony** [comment]
ok.

**Comment by janetbutts** [comment]
So can this be closed @freefony ?

**Comment by janetbutts** [comment]
@freefony, this gets to telerivet, but is not getting pushed to the database. Please review the code.

**Comment by jofomah** [comment]
am closing this because, it has be addressed by already merged in PRs.

**Pull request closed without merging**
